/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package green.ams;

import green.ams.components.StarRating;
import green.ams.components.RoundedBorder;
import green.ams.controllers.AreaController;
import green.ams.controllers.AttachementsController;
import javax.swing.table.DefaultTableModel;
import green.ams.controllers.SampleController;
import green.ams.controllers.UserController;
import green.ams.models.Area;
import green.ams.models.Attachements;
import green.ams.models.Consultation;
import green.ams.models.Evaluate;
import green.ams.models.Feedback;
import green.ams.models.Request;
import green.ams.models.Sample;
import green.ams.models.User;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.InputStream;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author Adham
 */
public class ADMIN extends javax.swing.JFrame {

    /**
     * Creates new form APP
     *
     * @param language
     */
    // Validation patterns
    private static final Pattern PHONE_PATTERN = Pattern.compile("^[+]?[0-9]{10,13}$");
    private static final Pattern PASSWORD_PATTERN = Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).{8,}$");

    // APP Frame Intialization
    APP app;

    // User Model Intializaition
    User user;

    // Area Model Intializaition
    Area area;

    // Attachements Model Intializaition
    Attachements attachements;

    // Evaluate Model Intializaition
    Evaluate evaluate;

    // Star Rating Component Intialization   
    StarRating ratingComponent;

    // Feedback Model Intializaition
    Feedback feedback;

    // Sample Model Intializaition
    Sample sample;

    // Consultation Model Intializaition
    Consultation consultation;

    // User Controller Intializaition
    UserController user_controller = new UserController();

    // Area Controller Intializaition
    AreaController area_controller = new AreaController();

    // Attachements Controller Intializaition
    AttachementsController attachements_controller = new AttachementsController();

    // Sample Controller Intialization
    SampleController sample_controller = new SampleController();

    // Current Date Intializaition
    Date current_date;

    private List<User> users_list;

    private List<Request> requests_list;

    private List<Sample> samples_list;

    private String sample_category = "Indoor";

    private JFileChooser fileChooser;
    private File[] files;
    private File file;

    // Add these variables to the class declaration
    private JScrollPane chatScrollPane;
    private JPanel messagesPanel;

    public ADMIN() {
        initComponents();

        Start();

        CustomeEdits();

        switchLanguage();

        setupChat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelHome = new javax.swing.JPanel();
        PanelHomeHeader = new javax.swing.JPanel();
        BtnSend = new javax.swing.JButton();
        BtnSignOut = new javax.swing.JButton();
        UserNavigation = new javax.swing.JPanel();
        nav_samples = new javax.swing.JLabel();
        nav_consultation = new javax.swing.JLabel();
        nav_evaltions = new javax.swing.JLabel();
        nav_finiancial = new javax.swing.JLabel();
        nav_users = new javax.swing.JLabel();
        PanelSamplesControl = new javax.swing.JPanel();
        PanelSampelsControlHeader = new javax.swing.JPanel();
        PanelTitle = new javax.swing.JLabel();
        nav_back = new javax.swing.JLabel();
        PanelSamplesControlContainer = new javax.swing.JPanel();
        ContainerTitle = new javax.swing.JPanel();
        LblSelectedTab = new javax.swing.JLabel();
        TabPane = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSamples = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableSamplesOrders = new javax.swing.JTable();
        PanelConsultant = new javax.swing.JPanel();
        PanelConsultantHeader = new javax.swing.JPanel();
        PanelTitle3 = new javax.swing.JLabel();
        nav_back3 = new javax.swing.JLabel();
        PanelConsultantionContainer = new javax.swing.JPanel();
        PanelControllers1 = new javax.swing.JPanel();
        LblConsultationTopic = new javax.swing.JLabel();
        PanelUsersChat = new javax.swing.JPanel();
        PanelUsersCards = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        panelItem1 = new green.ams.components.PanelItem();
        chatCard1 = new green.ams.components.ChatCard();
        chatCard2 = new green.ams.components.ChatCard();
        chatCard3 = new green.ams.components.ChatCard();
        chatCard4 = new green.ams.components.ChatCard();
        chatCard5 = new green.ams.components.ChatCard();
        chatCard6 = new green.ams.components.ChatCard();
        chatCard7 = new green.ams.components.ChatCard();
        chatCard8 = new green.ams.components.ChatCard();
        LblExit = new javax.swing.JLabel();
        PanelChat = new javax.swing.JPanel();
        PanelChatBody = new javax.swing.JPanel();
        PanelControllers = new javax.swing.JPanel();
        TFMessage = new javax.swing.JTextField();
        BtnMessageSend = new green.ams.components.GButton();
        PanelEvaluationsControl = new javax.swing.JPanel();
        PanelUsersControlHeader1 = new javax.swing.JPanel();
        PanelTitle2 = new javax.swing.JLabel();
        nav_back2 = new javax.swing.JLabel();
        PanelUsersControlContainer1 = new javax.swing.JPanel();
        ContainerTitle2 = new javax.swing.JPanel();
        LblSelectedTab2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableUsers1 = new javax.swing.JTable();
        PanelUsersControl = new javax.swing.JPanel();
        PanelUsersControlHeader = new javax.swing.JPanel();
        PanelTitle1 = new javax.swing.JLabel();
        nav_back1 = new javax.swing.JLabel();
        PanelUsersControlContainer = new javax.swing.JPanel();
        ContainerTitle1 = new javax.swing.JPanel();
        LblSelectedTab1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableUsers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("green/ams/Bundle"); // NOI18N
        setTitle(bundle.getString("ADMIN.title_1")); // NOI18N
        setBackground(new java.awt.Color(237, 233, 224));
        setForeground(new java.awt.Color(237, 233, 224));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setName("AppJFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        PanelHome.setBackground(new java.awt.Color(245, 255, 243));
        PanelHome.setMaximumSize(new java.awt.Dimension(1366, 768));
        PanelHome.setMinimumSize(new java.awt.Dimension(1366, 768));
        PanelHome.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelHome.setLayout(new java.awt.BorderLayout());

        PanelHomeHeader.setBackground(new java.awt.Color(245, 255, 243));
        PanelHomeHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 100));
        PanelHomeHeader.setMaximumSize(new java.awt.Dimension(1200, 1000));
        PanelHomeHeader.setMinimumSize(new java.awt.Dimension(500, 100));
        PanelHomeHeader.setPreferredSize(new java.awt.Dimension(1350, 50));
        PanelHomeHeader.setLayout(new java.awt.BorderLayout());

        BtnSend.setBackground(new java.awt.Color(97, 168, 149));
        BtnSend.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        BtnSend.setText(bundle.getString("ADMIN.BtnSend.text")); // NOI18N
        BtnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSendActionPerformed(evt);
            }
        });
        PanelHomeHeader.add(BtnSend, java.awt.BorderLayout.LINE_END);

        BtnSignOut.setBackground(new java.awt.Color(204, 255, 204));
        BtnSignOut.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        BtnSignOut.setText(bundle.getString("ADMIN.BtnSignOut.text")); // NOI18N
        BtnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignOutActionPerformed(evt);
            }
        });
        PanelHomeHeader.add(BtnSignOut, java.awt.BorderLayout.LINE_START);

        PanelHome.add(PanelHomeHeader, java.awt.BorderLayout.PAGE_START);

        UserNavigation.setBackground(new java.awt.Color(245, 255, 243));
        UserNavigation.setMinimumSize(new java.awt.Dimension(500, 500));
        UserNavigation.setPreferredSize(new java.awt.Dimension(1350, 330));
        UserNavigation.setLayout(new java.awt.GridLayout(2, 0));

        nav_samples.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        nav_samples.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nav_samples.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/nav-samples-removebg-preview.png"))); // NOI18N
        nav_samples.setText(bundle.getString("ADMIN.nav_samples.text")); // NOI18N
        nav_samples.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_samples.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav_samples.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nav_samples.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_samplesMouseClicked(evt);
            }
        });
        UserNavigation.add(nav_samples);

        nav_consultation.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        nav_consultation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nav_consultation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/nav-consultation-removebg-preview.png"))); // NOI18N
        nav_consultation.setText(bundle.getString("ADMIN.nav_consultation.text")); // NOI18N
        nav_consultation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_consultation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav_consultation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nav_consultation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_consultationMouseClicked(evt);
            }
        });
        UserNavigation.add(nav_consultation);

        nav_evaltions.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        nav_evaltions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nav_evaltions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/nav-evaulation-removebg-preview.png"))); // NOI18N
        nav_evaltions.setText(bundle.getString("ADMIN.nav_evaltions.text")); // NOI18N
        nav_evaltions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_evaltions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav_evaltions.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nav_evaltions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_evaltionsMouseClicked(evt);
            }
        });
        UserNavigation.add(nav_evaltions);

        nav_finiancial.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        nav_finiancial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nav_finiancial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/nav-finaical-removebg-preview.png"))); // NOI18N
        nav_finiancial.setText(bundle.getString("ADMIN.nav_finiancial.text")); // NOI18N
        nav_finiancial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_finiancial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav_finiancial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nav_finiancial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_finiancialMouseClicked(evt);
            }
        });
        UserNavigation.add(nav_finiancial);

        nav_users.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        nav_users.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nav_users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/nav-users-removebg-preview.png"))); // NOI18N
        nav_users.setText(bundle.getString("ADMIN.nav_users.text")); // NOI18N
        nav_users.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_users.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav_users.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nav_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_usersMouseClicked(evt);
            }
        });
        UserNavigation.add(nav_users);

        PanelHome.add(UserNavigation, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelHome);
        PanelHome.setBounds(0, 0, 1366, 730);

        PanelSamplesControl.setBackground(new java.awt.Color(237, 239, 230));
        PanelSamplesControl.setEnabled(false);
        PanelSamplesControl.setMaximumSize(new java.awt.Dimension(1366, 768));
        PanelSamplesControl.setMinimumSize(new java.awt.Dimension(1366, 768));
        PanelSamplesControl.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelSamplesControl.setLayout(new java.awt.BorderLayout());

        PanelSampelsControlHeader.setBackground(new java.awt.Color(203, 225, 196));
        PanelSampelsControlHeader.setPreferredSize(new java.awt.Dimension(1366, 50));
        PanelSampelsControlHeader.setLayout(new java.awt.BorderLayout());

        PanelTitle.setBackground(new java.awt.Color(203, 225, 196));
        PanelTitle.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        PanelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelTitle.setText(bundle.getString("ADMIN.PanelTitle.text")); // NOI18N
        PanelSampelsControlHeader.add(PanelTitle, java.awt.BorderLayout.CENTER);

        nav_back.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        nav_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/back-icon-removebg-preview.png"))); // NOI18N
        nav_back.setText(bundle.getString("ADMIN.nav_back.text")); // NOI18N
        nav_back.setAlignmentX(0.5F);
        nav_back.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));
        nav_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_back.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        nav_back.setMaximumSize(new java.awt.Dimension(122, 100));
        nav_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_backMouseClicked(evt);
            }
        });
        PanelSampelsControlHeader.add(nav_back, java.awt.BorderLayout.LINE_END);

        PanelSamplesControl.add(PanelSampelsControlHeader, java.awt.BorderLayout.PAGE_START);

        PanelSamplesControlContainer.setBackground(new java.awt.Color(237, 239, 230));
        PanelSamplesControlContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        PanelSamplesControlContainer.setPreferredSize(new java.awt.Dimension(1366, 588));
        PanelSamplesControlContainer.setLayout(new java.awt.BorderLayout());

        ContainerTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        ContainerTitle.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        ContainerTitle.setLayout(new javax.swing.BoxLayout(ContainerTitle, javax.swing.BoxLayout.LINE_AXIS));

        LblSelectedTab.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        LblSelectedTab.setText(bundle.getString("ADMIN.LblSelectedTab.text")); // NOI18N
        ContainerTitle.add(LblSelectedTab);

        PanelSamplesControlContainer.add(ContainerTitle, java.awt.BorderLayout.PAGE_START);

        TableSamples.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sample Name", "Sample Category", "Description", "Who Created", "Price", "Image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableSamples);

        TabPane.addTab("tab1", jScrollPane1);

        TableSamplesOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TableSamplesOrders);

        TabPane.addTab(bundle.getString("ADMIN.jScrollPane2.TabConstraints.tabTitle"), jScrollPane2); // NOI18N

        PanelSamplesControlContainer.add(TabPane, java.awt.BorderLayout.CENTER);
        TabPane.getAccessibleContext().setAccessibleName(bundle.getString("ADMIN.TabPane.AccessibleContext.accessibleName")); // NOI18N
        TabPane.getAccessibleContext().setAccessibleDescription(bundle.getString("ADMIN.TabPane.AccessibleContext.accessibleDescription")); // NOI18N

        PanelSamplesControl.add(PanelSamplesControlContainer, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelSamplesControl);
        PanelSamplesControl.setBounds(0, 0, 1366, 730);

        PanelConsultant.setBackground(new java.awt.Color(237, 239, 230));
        PanelConsultant.setEnabled(false);
        PanelConsultant.setMaximumSize(new java.awt.Dimension(1366, 768));
        PanelConsultant.setMinimumSize(new java.awt.Dimension(1366, 768));
        PanelConsultant.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelConsultant.setLayout(new java.awt.BorderLayout());

        PanelConsultantHeader.setBackground(new java.awt.Color(203, 225, 196));
        PanelConsultantHeader.setPreferredSize(new java.awt.Dimension(1366, 50));
        PanelConsultantHeader.setLayout(new java.awt.BorderLayout());

        PanelTitle3.setBackground(new java.awt.Color(203, 225, 196));
        PanelTitle3.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        PanelTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelTitle3.setText(bundle.getString("ADMIN.PanelTitle3.text")); // NOI18N
        PanelConsultantHeader.add(PanelTitle3, java.awt.BorderLayout.CENTER);

        nav_back3.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        nav_back3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/back-icon-removebg-preview.png"))); // NOI18N
        nav_back3.setText(bundle.getString("ADMIN.nav_back3.text")); // NOI18N
        nav_back3.setAlignmentX(0.5F);
        nav_back3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));
        nav_back3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_back3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        nav_back3.setMaximumSize(new java.awt.Dimension(122, 100));
        nav_back3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_back3MouseClicked(evt);
            }
        });
        PanelConsultantHeader.add(nav_back3, java.awt.BorderLayout.LINE_END);

        PanelConsultant.add(PanelConsultantHeader, java.awt.BorderLayout.PAGE_START);

        PanelConsultantionContainer.setBackground(new java.awt.Color(237, 239, 230));
        PanelConsultantionContainer.setPreferredSize(new java.awt.Dimension(1366, 588));
        PanelConsultantionContainer.setLayout(new java.awt.BorderLayout());

        PanelControllers1.setOpaque(false);
        PanelControllers1.setPreferredSize(new java.awt.Dimension(1366, 50));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5);
        flowLayout1.setAlignOnBaseline(true);
        PanelControllers1.setLayout(flowLayout1);

        LblConsultationTopic.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        LblConsultationTopic.setText(bundle.getString("ADMIN.LblConsultationTopic.text")); // NOI18N
        PanelControllers1.add(LblConsultationTopic);

        PanelConsultantionContainer.add(PanelControllers1, java.awt.BorderLayout.NORTH);

        PanelUsersChat.setBackground(new java.awt.Color(33, 104, 73));
        PanelUsersChat.setPreferredSize(new java.awt.Dimension(270, 668));
        PanelUsersChat.setLayout(new java.awt.BorderLayout());

        PanelUsersCards.setBackground(new java.awt.Color(255, 255, 255));
        PanelUsersCards.setOpaque(false);
        PanelUsersCards.setPreferredSize(new java.awt.Dimension(300, 630));
        PanelUsersCards.setLayout(new javax.swing.BoxLayout(PanelUsersCards, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setOpaque(false);
        jScrollPane4.setPreferredSize(PanelUsersCards.getPreferredSize());

        panelItem1.setBackground(new java.awt.Color(33, 104, 73));
        panelItem1.setMinimumSize(new java.awt.Dimension(100, 100));
        panelItem1.setPreferredSize(PanelUsersCards.getPreferredSize());

        chatCard1.setPreferredSize(new java.awt.Dimension(230, 100));
        panelItem1.add(chatCard1);

        chatCard2.setPreferredSize(new java.awt.Dimension(230, 100));
        panelItem1.add(chatCard2);

        chatCard3.setPreferredSize(new java.awt.Dimension(230, 100));
        panelItem1.add(chatCard3);

        chatCard4.setPreferredSize(new java.awt.Dimension(230, 100));
        panelItem1.add(chatCard4);

        chatCard5.setPreferredSize(new java.awt.Dimension(230, 100));
        panelItem1.add(chatCard5);

        chatCard6.setPreferredSize(new java.awt.Dimension(230, 100));
        panelItem1.add(chatCard6);

        chatCard7.setPreferredSize(new java.awt.Dimension(230, 100));
        panelItem1.add(chatCard7);

        chatCard8.setPreferredSize(new java.awt.Dimension(230, 100));
        panelItem1.add(chatCard8);

        jScrollPane4.setViewportView(panelItem1);
        panelItem1.getAccessibleContext().setAccessibleParent(jScrollPane4);

        PanelUsersCards.add(jScrollPane4);

        PanelUsersChat.add(PanelUsersCards, java.awt.BorderLayout.CENTER);

        LblExit.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        LblExit.setForeground(new java.awt.Color(255, 255, 255));
        LblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/exit-icon-removebg-preview.png"))); // NOI18N
        LblExit.setText(bundle.getString("ADMIN.LblExit.text")); // NOI18N
        PanelUsersChat.add(LblExit, java.awt.BorderLayout.PAGE_END);

        PanelConsultantionContainer.add(PanelUsersChat, java.awt.BorderLayout.LINE_START);

        PanelChat.setLayout(new java.awt.BorderLayout());

        PanelChatBody.setBackground(new java.awt.Color(255, 255, 255));
        PanelChatBody.setMaximumSize(new java.awt.Dimension(32767, 500));
        PanelChatBody.setPreferredSize(new java.awt.Dimension(1366, 573));

        javax.swing.GroupLayout PanelChatBodyLayout = new javax.swing.GroupLayout(PanelChatBody);
        PanelChatBody.setLayout(PanelChatBodyLayout);
        PanelChatBodyLayout.setHorizontalGroup(
            PanelChatBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
        );
        PanelChatBodyLayout.setVerticalGroup(
            PanelChatBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        PanelChat.add(PanelChatBody, java.awt.BorderLayout.CENTER);

        PanelControllers.setBackground(new java.awt.Color(255, 255, 255));
        PanelControllers.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        PanelControllers.setPreferredSize(new java.awt.Dimension(1366, 90));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout();
        flowLayout2.setAlignOnBaseline(true);
        PanelControllers.setLayout(flowLayout2);

        TFMessage.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        TFMessage.setText(bundle.getString("ADMIN.TFMessage.text")); // NOI18N
        TFMessage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 104, 73), 3, true));
        TFMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TFMessage.setMaximumSize(new java.awt.Dimension(100, 200));
        TFMessage.setPreferredSize(new java.awt.Dimension(980, 35));
        TFMessage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TFMessageFocusGained(evt);
            }
        });
        PanelControllers.add(TFMessage);

        BtnMessageSend.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        BtnMessageSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/send-icon-removebg-preview.png"))); // NOI18N
        BtnMessageSend.setText(bundle.getString("ADMIN.BtnMessageSend.text")); // NOI18N
        BtnMessageSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMessageSendActionPerformed(evt);
            }
        });
        PanelControllers.add(BtnMessageSend);

        PanelChat.add(PanelControllers, java.awt.BorderLayout.PAGE_END);

        PanelConsultantionContainer.add(PanelChat, java.awt.BorderLayout.CENTER);

        PanelConsultant.add(PanelConsultantionContainer, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelConsultant);
        PanelConsultant.setBounds(0, 0, 1366, 730);

        PanelEvaluationsControl.setBackground(new java.awt.Color(237, 239, 230));
        PanelEvaluationsControl.setEnabled(false);
        PanelEvaluationsControl.setMaximumSize(new java.awt.Dimension(1366, 768));
        PanelEvaluationsControl.setMinimumSize(new java.awt.Dimension(1366, 768));
        PanelEvaluationsControl.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelEvaluationsControl.setLayout(new java.awt.BorderLayout());

        PanelUsersControlHeader1.setBackground(new java.awt.Color(203, 225, 196));
        PanelUsersControlHeader1.setPreferredSize(new java.awt.Dimension(1366, 50));
        PanelUsersControlHeader1.setLayout(new java.awt.BorderLayout());

        PanelTitle2.setBackground(new java.awt.Color(203, 225, 196));
        PanelTitle2.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        PanelTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelTitle2.setText(bundle.getString("ADMIN.PanelTitle2.text")); // NOI18N
        PanelUsersControlHeader1.add(PanelTitle2, java.awt.BorderLayout.CENTER);

        nav_back2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        nav_back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/back-icon-removebg-preview.png"))); // NOI18N
        nav_back2.setText(bundle.getString("ADMIN.nav_back2.text")); // NOI18N
        nav_back2.setAlignmentX(0.5F);
        nav_back2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));
        nav_back2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_back2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        nav_back2.setMaximumSize(new java.awt.Dimension(122, 100));
        nav_back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_back2MouseClicked(evt);
            }
        });
        PanelUsersControlHeader1.add(nav_back2, java.awt.BorderLayout.LINE_END);

        PanelEvaluationsControl.add(PanelUsersControlHeader1, java.awt.BorderLayout.PAGE_START);

        PanelUsersControlContainer1.setBackground(new java.awt.Color(237, 239, 230));
        PanelUsersControlContainer1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        PanelUsersControlContainer1.setPreferredSize(new java.awt.Dimension(1366, 588));
        PanelUsersControlContainer1.setLayout(new java.awt.BorderLayout());

        ContainerTitle2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        ContainerTitle2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        ContainerTitle2.setLayout(new javax.swing.BoxLayout(ContainerTitle2, javax.swing.BoxLayout.LINE_AXIS));

        LblSelectedTab2.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        LblSelectedTab2.setText(bundle.getString("ADMIN.LblSelectedTab2.text")); // NOI18N
        ContainerTitle2.add(LblSelectedTab2);

        PanelUsersControlContainer1.add(ContainerTitle2, java.awt.BorderLayout.PAGE_START);

        TableUsers1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Full Name", "Email", "Address", "Phone Number", "Role", "CreatedDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TableUsers1);

        PanelUsersControlContainer1.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        PanelEvaluationsControl.add(PanelUsersControlContainer1, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelEvaluationsControl);
        PanelEvaluationsControl.setBounds(0, 0, 1366, 730);

        PanelUsersControl.setBackground(new java.awt.Color(237, 239, 230));
        PanelUsersControl.setEnabled(false);
        PanelUsersControl.setMaximumSize(new java.awt.Dimension(1366, 768));
        PanelUsersControl.setMinimumSize(new java.awt.Dimension(1366, 768));
        PanelUsersControl.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelUsersControl.setLayout(new java.awt.BorderLayout());

        PanelUsersControlHeader.setBackground(new java.awt.Color(203, 225, 196));
        PanelUsersControlHeader.setPreferredSize(new java.awt.Dimension(1366, 50));
        PanelUsersControlHeader.setLayout(new java.awt.BorderLayout());

        PanelTitle1.setBackground(new java.awt.Color(203, 225, 196));
        PanelTitle1.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        PanelTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelTitle1.setText(bundle.getString("ADMIN.PanelTitle1.text")); // NOI18N
        PanelUsersControlHeader.add(PanelTitle1, java.awt.BorderLayout.CENTER);

        nav_back1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        nav_back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/back-icon-removebg-preview.png"))); // NOI18N
        nav_back1.setText(bundle.getString("ADMIN.nav_back1.text")); // NOI18N
        nav_back1.setAlignmentX(0.5F);
        nav_back1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));
        nav_back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_back1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        nav_back1.setMaximumSize(new java.awt.Dimension(122, 100));
        nav_back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_back1MouseClicked(evt);
            }
        });
        PanelUsersControlHeader.add(nav_back1, java.awt.BorderLayout.LINE_END);

        PanelUsersControl.add(PanelUsersControlHeader, java.awt.BorderLayout.PAGE_START);

        PanelUsersControlContainer.setBackground(new java.awt.Color(237, 239, 230));
        PanelUsersControlContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        PanelUsersControlContainer.setPreferredSize(new java.awt.Dimension(1366, 588));
        PanelUsersControlContainer.setLayout(new java.awt.BorderLayout());

        ContainerTitle1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        ContainerTitle1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        ContainerTitle1.setLayout(new javax.swing.BoxLayout(ContainerTitle1, javax.swing.BoxLayout.LINE_AXIS));

        LblSelectedTab1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        LblSelectedTab1.setText(bundle.getString("ADMIN.LblSelectedTab1.text")); // NOI18N
        ContainerTitle1.add(LblSelectedTab1);

        PanelUsersControlContainer.add(ContainerTitle1, java.awt.BorderLayout.PAGE_START);

        TableUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Full Name", "Email", "Address", "Phone Number", "Role", "CreatedDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TableUsers);

        PanelUsersControlContainer.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        PanelUsersControl.add(PanelUsersControlContainer, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelUsersControl);
        PanelUsersControl.setBounds(0, 0, 1366, 730);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nav_back3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_back3MouseClicked
        // TODO add your handling code here:

        MoveTo(PanelConsultant, PanelHome);
    }//GEN-LAST:event_nav_back3MouseClicked

    private void TFMessageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFMessageFocusGained
        // TODO add your handling code here:

        if (TFMessage.getText().equals("Write your message here")) {
            TFMessage.setText("");
        }
    }//GEN-LAST:event_TFMessageFocusGained

    private void BtnMessageSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMessageSendActionPerformed
        // TODO add your handling code here:

        sendMessage();

    }//GEN-LAST:event_BtnMessageSendActionPerformed

    private void nav_samplesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_samplesMouseClicked
        // TODO add your handling code here:

        // Fetch data
        samples_list = new ArrayList<>();
        samples_list = sample_controller.SamplesTable();

        // Define table model with column names
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 4) {
                    return ImageIcon.class; // Image column
                }
                return String.class;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Make all cells non-editable
            }
        };

        model.addColumn("Sample Name");
        model.addColumn("Sample Category");
        model.addColumn("Sample Description");
        model.addColumn("Sample Price");
        model.addColumn("Sample Image");

// Load rows into model
        for (Sample sample : samples_list) {
            ImageIcon icon = null;
            try {
                InputStream imgStream = sample.getImageStream();
                if (imgStream != null) {
                    BufferedImage img = ImageIO.read(imgStream);
                    if (img != null) {
                        Image scaledImg = img.getScaledInstance(80, 60, Image.SCALE_SMOOTH);
                        icon = new ImageIcon(scaledImg);
                    }
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }

            model.addRow(new Object[]{
                sample.getName(),
                sample.getCategory(),
                sample.getDescription(),
                sample.getPrice(),
                icon
            });
        }

// Apply the model to your JTable
        TableSamples.setModel(model);

// Set row height to fit images
        TableSamples.setRowHeight(70);

        MoveTo(PanelHome, PanelSamplesControl);

    }//GEN-LAST:event_nav_samplesMouseClicked

    private void nav_consultationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_consultationMouseClicked
        // TODO add your handling code here:

        user = new User();
        
        user_controller.getConsultationMessages();
                
                
        MoveTo(PanelHome, PanelConsultant);
    }//GEN-LAST:event_nav_consultationMouseClicked

    private void nav_evaltionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_evaltionsMouseClicked
        // TODO add your handling code here:

        MoveTo(PanelHome, PanelEvaluationsControl);

    }//GEN-LAST:event_nav_evaltionsMouseClicked

    private void nav_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_usersMouseClicked
        // TODO add your handling code here:

        users_list = new ArrayList<>();

        users_list = user_controller.UsersTable();

        for (User user1 : users_list) {
            System.out.println(user1.getId());
            System.out.println(user1.getFull_name());
            System.out.println(user1.getEmail());
            System.out.println(user1.getAddress());
            System.out.println(user1.getPhone_number());
            System.out.println(user1.getPhone_number());
            System.out.println(user1.getCreated_date());
        }

        // Define table model with column names
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Full Name");
        model.addColumn("Email");
        model.addColumn("Address");
        model.addColumn("Phone Number");
        model.addColumn("Role");
        model.addColumn("Created Date");

        // Load rows into model
        for (User user : users_list) {
            model.addRow(new Object[]{
                user.getFull_name(),
                user.getEmail(),
                user.getAddress(),
                user.getPhone_number(),
                user.getRole(),
                user.getCreated_date()
            });
        }
        TableUsers.setModel(model);

        MoveTo(PanelHome, PanelUsersControl);

    }//GEN-LAST:event_nav_usersMouseClicked

    private void nav_finiancialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_finiancialMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nav_finiancialMouseClicked

    private void nav_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_backMouseClicked
        // TODO add your handling code here:
        MoveTo(PanelSamplesControl, PanelHome);

    }//GEN-LAST:event_nav_backMouseClicked

    private void nav_back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_back1MouseClicked
        // TODO add your handling code here:
        MoveTo(PanelUsersControl, PanelHome);

    }//GEN-LAST:event_nav_back1MouseClicked

    private void BtnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignOutActionPerformed
        // TODO add your handling code here:

        user = null;
        this.dispose();
        app = new APP();
        app.setVisible(true);
    }//GEN-LAST:event_BtnSignOutActionPerformed

    private void BtnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSendActionPerformed

    private void nav_back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_back2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nav_back2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ADMIN().setVisible(true);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private green.ams.components.GButton BtnMessageSend;
    private javax.swing.JButton BtnSend;
    private javax.swing.JButton BtnSignOut;
    private javax.swing.JPanel ContainerTitle;
    private javax.swing.JPanel ContainerTitle1;
    private javax.swing.JPanel ContainerTitle2;
    private javax.swing.JLabel LblConsultationTopic;
    private javax.swing.JLabel LblExit;
    private javax.swing.JLabel LblSelectedTab;
    private javax.swing.JLabel LblSelectedTab1;
    private javax.swing.JLabel LblSelectedTab2;
    private javax.swing.JPanel PanelChat;
    private javax.swing.JPanel PanelChatBody;
    private javax.swing.JPanel PanelConsultant;
    private javax.swing.JPanel PanelConsultantHeader;
    private javax.swing.JPanel PanelConsultantionContainer;
    private javax.swing.JPanel PanelControllers;
    private javax.swing.JPanel PanelControllers1;
    private javax.swing.JPanel PanelEvaluationsControl;
    private javax.swing.JPanel PanelHome;
    private javax.swing.JPanel PanelHomeHeader;
    private javax.swing.JPanel PanelSampelsControlHeader;
    private javax.swing.JPanel PanelSamplesControl;
    private javax.swing.JPanel PanelSamplesControlContainer;
    private javax.swing.JLabel PanelTitle;
    private javax.swing.JLabel PanelTitle1;
    private javax.swing.JLabel PanelTitle2;
    private javax.swing.JLabel PanelTitle3;
    private javax.swing.JPanel PanelUsersCards;
    private javax.swing.JPanel PanelUsersChat;
    private javax.swing.JPanel PanelUsersControl;
    private javax.swing.JPanel PanelUsersControlContainer;
    private javax.swing.JPanel PanelUsersControlContainer1;
    private javax.swing.JPanel PanelUsersControlHeader;
    private javax.swing.JPanel PanelUsersControlHeader1;
    private javax.swing.JTextField TFMessage;
    private javax.swing.JTabbedPane TabPane;
    private javax.swing.JTable TableSamples;
    private javax.swing.JTable TableSamplesOrders;
    private javax.swing.JTable TableUsers;
    private javax.swing.JTable TableUsers1;
    private javax.swing.JPanel UserNavigation;
    private green.ams.components.ChatCard chatCard1;
    private green.ams.components.ChatCard chatCard2;
    private green.ams.components.ChatCard chatCard3;
    private green.ams.components.ChatCard chatCard4;
    private green.ams.components.ChatCard chatCard5;
    private green.ams.components.ChatCard chatCard6;
    private green.ams.components.ChatCard chatCard7;
    private green.ams.components.ChatCard chatCard8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel nav_back;
    private javax.swing.JLabel nav_back1;
    private javax.swing.JLabel nav_back2;
    private javax.swing.JLabel nav_back3;
    private javax.swing.JLabel nav_consultation;
    private javax.swing.JLabel nav_evaltions;
    private javax.swing.JLabel nav_finiancial;
    private javax.swing.JLabel nav_samples;
    private javax.swing.JLabel nav_users;
    private green.ams.components.PanelItem panelItem1;
    // End of variables declaration//GEN-END:variables

    private void Start() {

        PanelHome.setVisible(true);
        PanelSamplesControl.setVisible(false);
        PanelUsersControl.setVisible(false);
        PanelConsultant.setVisible(false);

    }

    private void CustomeEdits() {

        TabPane.setTitleAt(0, "All Samples Table");
        TabPane.setTitleAt(1, "All Samples Orders");

    }

    private void MoveTo(JPanel o1, JPanel o2) {
        o1.setVisible(false);
        o2.setVisible(true);
    }

    private void switchLanguage() {

        // Reload ResourceBundle with correct package
        GLOBAL.bundle = ResourceBundle.getBundle("green.ams.Bundle", GLOBAL.currentLocale);

        // Update UI Components
        GLOBAL.updateTextFields(this, "MEWA", GLOBAL.bundle);
    }

    // Add this method to set up the chat UI
    private void setupChat() {
        messagesPanel = new JPanel();
        messagesPanel.setLayout(new BoxLayout(messagesPanel, BoxLayout.Y_AXIS));
        messagesPanel.setBackground(new Color(237, 239, 230));

        chatScrollPane = new JScrollPane(messagesPanel);
        chatScrollPane.setBorder(null);
        chatScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        chatScrollPane.getVerticalScrollBar().setUnitIncrement(16);

        // Replace the existing PanelChatBody layout
        PanelChatBody.setLayout(new BorderLayout());
        PanelChatBody.removeAll();
        PanelChatBody.add(chatScrollPane, BorderLayout.CENTER);
        PanelChatBody.revalidate();
        PanelChatBody.repaint();

        // Add action listeners for sending messages
        BtnMessageSend.addActionListener(e -> sendMessage());
        TFMessage.addActionListener(e -> sendMessage());
    }

    // Add this method to handle message sending
    private void sendMessage() {
        String text = TFMessage.getText().trim();
        if (!text.isEmpty()) {
            addMessage(text); // User message
            TFMessage.setText("");

            // Simulate consultant reply after 1 second
            new Timer(1000, evt -> {
                addMessage(user_controller.getMessages(GLOBAL.user_id, text));
                ((Timer) evt.getSource()).stop();
            }).start();
        }
    }

    // Add this method to create message bubbles
    private void addMessage(String text) {
        String topic = "Public Chat";

        consultation = new Consultation();
        consultation.setUser_id(GLOBAL.user_id);
        consultation.setTopic(topic);
        consultation.setMessage(text);

        JPanel wrapperPanel = new JPanel(new BorderLayout());
        wrapperPanel.setOpaque(false);  // matches background
        JPanel bubble = createResponsiveBubble(text);

        wrapperPanel.add(bubble, BorderLayout.WEST);

        wrapperPanel.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
        messagesPanel.add(wrapperPanel);
        messagesPanel.add(Box.createVerticalStrut(8));

        messagesPanel.revalidate();
        messagesPanel.repaint();

        SwingUtilities.invokeLater(() -> {
            JScrollBar vertical = chatScrollPane.getVerticalScrollBar();
            vertical.setValue(vertical.getMaximum());
        });

        user_controller.Consultation(consultation);

    }

    private JPanel createResponsiveBubble(String text) {
        JTextArea messageText = new JTextArea(text);
        messageText.setLineWrap(true);
        messageText.setWrapStyleWord(true);
        messageText.setEditable(false);
        messageText.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        messageText.setBackground(Color.WHITE);
        messageText.setForeground(Color.DARK_GRAY);
        messageText.setBorder(BorderFactory.createEmptyBorder(10, 14, 10, 14));

        JPanel bubble = new JPanel(new BorderLayout());
        bubble.setOpaque(true);
        bubble.setBackground(messageText.getBackground());
        bubble.add(messageText, BorderLayout.CENTER);

        bubble.setBorder(BorderFactory.createCompoundBorder(
                new RoundedBorder(12),
                BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));

        // Responsive width calculation
        int maxWidth = (int) (chatScrollPane.getViewport().getWidth() * 0.6); // 60% of available width
        messageText.setMaximumSize(new Dimension(maxWidth, Integer.MAX_VALUE));

        // Let messageText expand as wide as needed
        messageText.setPreferredSize(new Dimension(maxWidth, messageText.getPreferredSize().height));

        return bubble;
    }

}
