/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package green.ams;

import green.ams.components.StarRating;
import green.ams.controllers.UserController;
import green.ams.models.Evaluate;
import green.ams.models.Feedback;
import green.ams.models.User;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Frame;
import java.sql.Date;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.plaf.PanelUI;
import org.w3c.dom.css.RGBColor;

/**
 *
 * @author Adham
 */
public class USER extends javax.swing.JFrame {

    /**
     * Creates new form APP
     *
     * @param language
     */
    public USER() {
        initComponents();

        Start();

        switchLanguage();
    }

    // APP Frame Intialization
    APP app;

    // User Model Intializaition
    User user;

    // Evaluate Model Intializaition
    Evaluate evaluate;

    // Feedback Model Intializaition
    Feedback feedback;

    // User Authentication Intializaition
    UserController user_controller = new UserController();

    // Current Date Intializaition
    Date current_date;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        PanelHome = new javax.swing.JPanel();
        BtnSignOut = new javax.swing.JButton();
        BtnSupport = new javax.swing.JLabel();
        BtnSetting = new javax.swing.JLabel();
        BtnUserProfile = new javax.swing.JLabel();
        UserNavigation = new javax.swing.JPanel();
        nav_rate = new javax.swing.JLabel();
        nav_consultant = new javax.swing.JLabel();
        nav_sample = new javax.swing.JLabel();
        nav_location = new javax.swing.JLabel();
        PanelFeedback = new javax.swing.JPanel();
        PanelTitle = new javax.swing.JLabel();
        FormFeedback = new javax.swing.JPanel();
        PanelContainer = new javax.swing.JPanel();
        PanelLeft = new javax.swing.JPanel();
        LblMessage = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        TAMessage = new javax.swing.JTextArea();
        PanelRight = new javax.swing.JPanel();
        LblName = new javax.swing.JLabel();
        TFFullName = new javax.swing.JTextField();
        LblEmailAddress = new javax.swing.JLabel();
        TFEmailAddress = new javax.swing.JTextField();
        LblPhone = new javax.swing.JLabel();
        TFPhone = new javax.swing.JTextField();
        PanelButtons = new javax.swing.JPanel();
        BtnSend = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        PanelUserProfile = new javax.swing.JPanel();
        FormUserProfile = new javax.swing.JPanel();
        PanelContainer1 = new javax.swing.JPanel();
        PanelLeft1 = new javax.swing.JPanel();
        LblName2 = new javax.swing.JLabel();
        PanelRight1 = new javax.swing.JPanel();
        LblUserName = new javax.swing.JLabel();
        UPLblFullName = new javax.swing.JLabel();
        UPTFFullName = new javax.swing.JTextField();
        UPLblAddress = new javax.swing.JLabel();
        UPTFAddress = new javax.swing.JTextField();
        UPLblPhone = new javax.swing.JLabel();
        UPTFPhone = new javax.swing.JTextField();
        UPLblResetPassword = new javax.swing.JLabel();
        UPTFResetPassword = new javax.swing.JTextField();
        PanelButtons1 = new javax.swing.JPanel();
        BtnSave = new javax.swing.JButton();
        BtnBack1 = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("green/ams/Bundle"); // NOI18N
        jMenu1.setText(bundle.getString("USER.jMenu1.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(bundle.getString("USER.title")); // NOI18N
        setBackground(new java.awt.Color(237, 233, 224));
        setForeground(new java.awt.Color(237, 233, 224));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setName("AppJFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        PanelHome.setBackground(new java.awt.Color(245, 255, 243));
        PanelHome.setMaximumSize(new java.awt.Dimension(1366, 768));
        PanelHome.setMinimumSize(new java.awt.Dimension(1366, 768));
        PanelHome.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnSignOut.setBackground(new java.awt.Color(204, 255, 204));
        BtnSignOut.setFont(new java.awt.Font("Traditional Arabic", 1, 12)); // NOI18N
        BtnSignOut.setText(bundle.getString("USER.BtnSignOut.text")); // NOI18N
        BtnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSignOutActionPerformed(evt);
            }
        });
        PanelHome.add(BtnSignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        BtnSupport.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        BtnSupport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/support-removebg-preview.png"))); // NOI18N
        BtnSupport.setText(bundle.getString("USER.BtnSupport.text")); // NOI18N
        BtnSupport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSupport.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        PanelHome.add(BtnSupport, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 668, 280, 60));

        BtnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/user-removebg-preview.png"))); // NOI18N
        BtnSetting.setText(bundle.getString("USER.BtnSetting.text")); // NOI18N
        BtnSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSettingMouseClicked(evt);
            }
        });
        PanelHome.add(BtnSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, 70, 70));

        BtnUserProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/settings-removebg-preview.png"))); // NOI18N
        BtnUserProfile.setText(bundle.getString("USER.BtnUserProfile.text")); // NOI18N
        BtnUserProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelHome.add(BtnUserProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 70, 70));

        UserNavigation.setBackground(new java.awt.Color(245, 255, 243));
        UserNavigation.setMinimumSize(new java.awt.Dimension(500, 500));
        UserNavigation.setPreferredSize(new java.awt.Dimension(1350, 330));
        UserNavigation.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 20));

        nav_rate.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        nav_rate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/rate-removebg-preview.png"))); // NOI18N
        nav_rate.setText(bundle.getString("USER.nav_rate.text")); // NOI18N
        nav_rate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_rate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav_rate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nav_rate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nav_rateMouseClicked(evt);
            }
        });
        UserNavigation.add(nav_rate);

        nav_consultant.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        nav_consultant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/consultant-removebg-preview.png"))); // NOI18N
        nav_consultant.setText(bundle.getString("USER.nav_consultant.text")); // NOI18N
        nav_consultant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_consultant.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav_consultant.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        UserNavigation.add(nav_consultant);

        nav_sample.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        nav_sample.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/sample-removebg-preview.png"))); // NOI18N
        nav_sample.setText(bundle.getString("USER.nav_sample.text")); // NOI18N
        nav_sample.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_sample.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav_sample.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        UserNavigation.add(nav_sample);

        nav_location.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        nav_location.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/location-removebg-preview.png"))); // NOI18N
        nav_location.setText(bundle.getString("USER.nav_location.text")); // NOI18N
        nav_location.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nav_location.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nav_location.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        UserNavigation.add(nav_location);

        PanelHome.add(UserNavigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1350, -1));

        getContentPane().add(PanelHome);
        PanelHome.setBounds(0, 0, 1366, 768);

        PanelFeedback.setBackground(new java.awt.Color(245, 255, 243));
        PanelFeedback.setEnabled(false);
        PanelFeedback.setMaximumSize(new java.awt.Dimension(1366, 768));
        PanelFeedback.setMinimumSize(new java.awt.Dimension(1366, 768));
        PanelFeedback.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelFeedback.setLayout(new java.awt.BorderLayout(0, 30));

        PanelTitle.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        PanelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelTitle.setText(bundle.getString("USER.PanelTitle.text")); // NOI18N
        PanelFeedback.add(PanelTitle, java.awt.BorderLayout.PAGE_START);

        FormFeedback.setMaximumSize(new java.awt.Dimension(1366, 768));
        FormFeedback.setMinimumSize(new java.awt.Dimension(100, 100));
        FormFeedback.setPreferredSize(new java.awt.Dimension(1366, 300));
        FormFeedback.setLayout(new java.awt.BorderLayout());

        PanelContainer.setBackground(new java.awt.Color(245, 255, 243));
        PanelContainer.setMaximumSize(new java.awt.Dimension(1366, 768));
        PanelContainer.setMinimumSize(new java.awt.Dimension(100, 100));
        PanelContainer.setPreferredSize(new java.awt.Dimension(768, 100));

        PanelLeft.setBackground(new java.awt.Color(245, 255, 243));
        PanelLeft.setMaximumSize(new java.awt.Dimension(1366, 768));
        PanelLeft.setMinimumSize(new java.awt.Dimension(100, 100));
        PanelLeft.setPreferredSize(new java.awt.Dimension(500, 300));
        PanelLeft.setLayout(new java.awt.BorderLayout());

        LblMessage.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        LblMessage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblMessage.setText(bundle.getString("USER.LblMessage.text")); // NOI18N
        PanelLeft.add(LblMessage, java.awt.BorderLayout.PAGE_START);

        ScrollPane.setMaximumSize(new java.awt.Dimension(300, 300));
        ScrollPane.setPreferredSize(new java.awt.Dimension(300, 200));

        TAMessage.setColumns(20);
        TAMessage.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        TAMessage.setLineWrap(true);
        TAMessage.setRows(5);
        TAMessage.setWrapStyleWord(true);
        TAMessage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 104, 73), 3, true));
        TAMessage.setMaximumSize(new java.awt.Dimension(300, 300));
        TAMessage.setPreferredSize(new java.awt.Dimension(300, 200));
        ScrollPane.setViewportView(TAMessage);

        PanelLeft.add(ScrollPane, java.awt.BorderLayout.CENTER);

        PanelRight.setBackground(new java.awt.Color(245, 255, 243));
        PanelRight.setPreferredSize(new java.awt.Dimension(500, 500));
        PanelRight.setLayout(new java.awt.GridLayout(6, 0, 0, 5));

        LblName.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        LblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblName.setText(bundle.getString("USER.LblName.text")); // NOI18N
        PanelRight.add(LblName);

        TFFullName.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        TFFullName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TFFullName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 104, 73), 3, true));
        TFFullName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TFFullName.setMaximumSize(new java.awt.Dimension(100, 200));
        PanelRight.add(TFFullName);

        LblEmailAddress.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        LblEmailAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblEmailAddress.setText(bundle.getString("USER.LblEmailAddress.text")); // NOI18N
        PanelRight.add(LblEmailAddress);

        TFEmailAddress.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        TFEmailAddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TFEmailAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 104, 73), 3, true));
        TFEmailAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PanelRight.add(TFEmailAddress);

        LblPhone.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        LblPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblPhone.setText(bundle.getString("USER.LblPhone.text")); // NOI18N
        PanelRight.add(LblPhone);

        TFPhone.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        TFPhone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TFPhone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 104, 73), 3, true));
        TFPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PanelRight.add(TFPhone);

        PanelButtons.setBackground(new java.awt.Color(245, 255, 243));

        BtnSend.setBackground(new java.awt.Color(33, 104, 73));
        BtnSend.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        BtnSend.setForeground(new java.awt.Color(255, 255, 255));
        BtnSend.setText(bundle.getString("USER.BtnSend.text")); // NOI18N
        BtnSend.setAlignmentY(0.0F);
        BtnSend.setBorder(null);
        BtnSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSend.setDefaultCapable(false);
        BtnSend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSend.setMaximumSize(new java.awt.Dimension(80, 30));
        BtnSend.setMinimumSize(new java.awt.Dimension(40, 15));
        BtnSend.setPreferredSize(new java.awt.Dimension(100, 40));
        BtnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSendActionPerformed(evt);
            }
        });
        PanelButtons.add(BtnSend);

        BtnBack.setBackground(new java.awt.Color(121, 110, 113));
        BtnBack.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        BtnBack.setForeground(new java.awt.Color(255, 255, 255));
        BtnBack.setText(bundle.getString("USER.BtnBack.text")); // NOI18N
        BtnBack.setAlignmentY(0.0F);
        BtnBack.setBorder(null);
        BtnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBack.setDefaultCapable(false);
        BtnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBack.setMaximumSize(new java.awt.Dimension(80, 30));
        BtnBack.setMinimumSize(new java.awt.Dimension(40, 15));
        BtnBack.setPreferredSize(new java.awt.Dimension(100, 40));
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        PanelButtons.add(BtnBack);

        javax.swing.GroupLayout PanelContainerLayout = new javax.swing.GroupLayout(PanelContainer);
        PanelContainer.setLayout(PanelContainerLayout);
        PanelContainerLayout.setHorizontalGroup(
            PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContainerLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(PanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(PanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelContainerLayout.createSequentialGroup()
                .addComponent(PanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelContainerLayout.setVerticalGroup(
            PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelRight, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200)
                .addComponent(PanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        FormFeedback.add(PanelContainer, java.awt.BorderLayout.CENTER);

        PanelFeedback.add(FormFeedback, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelFeedback);
        PanelFeedback.setBounds(0, 0, 1366, 768);

        PanelUserProfile.setBackground(new java.awt.Color(245, 255, 243));
        PanelUserProfile.setAlignmentX(0.15F);
        PanelUserProfile.setEnabled(false);
        PanelUserProfile.setMaximumSize(new java.awt.Dimension(1366, 768));
        PanelUserProfile.setMinimumSize(new java.awt.Dimension(1366, 768));
        PanelUserProfile.setPreferredSize(new java.awt.Dimension(1366, 768));
        PanelUserProfile.setLayout(new java.awt.BorderLayout(0, 30));

        FormUserProfile.setBackground(new java.awt.Color(245, 255, 243));
        FormUserProfile.setMaximumSize(new java.awt.Dimension(1366, 768));
        FormUserProfile.setPreferredSize(new java.awt.Dimension(1366, 300));
        FormUserProfile.setLayout(new javax.swing.BoxLayout(FormUserProfile, javax.swing.BoxLayout.PAGE_AXIS));

        PanelContainer1.setBackground(new java.awt.Color(245, 255, 243));
        PanelContainer1.setMaximumSize(new java.awt.Dimension(1366, 768));
        PanelContainer1.setMinimumSize(new java.awt.Dimension(100, 100));
        PanelContainer1.setPreferredSize(new java.awt.Dimension(768, 646));
        PanelContainer1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        PanelLeft1.setBackground(new java.awt.Color(245, 255, 243));
        PanelLeft1.setPreferredSize(new java.awt.Dimension(500, 500));
        PanelLeft1.setLayout(new java.awt.GridLayout(1, 0));

        LblName2.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        LblName2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/score-removebg-preview.png"))); // NOI18N
        LblName2.setText(bundle.getString("USER.LblName2.text")); // NOI18N
        LblName2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LblName2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblName2.setMinimumSize(new java.awt.Dimension(50, 110));
        LblName2.setPreferredSize(new java.awt.Dimension(50, 110));
        LblName2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PanelLeft1.add(LblName2);

        PanelContainer1.add(PanelLeft1);

        PanelRight1.setBackground(new java.awt.Color(245, 255, 243));
        PanelRight1.setMinimumSize(new java.awt.Dimension(500, 725));
        PanelRight1.setPreferredSize(new java.awt.Dimension(500, 600));
        PanelRight1.setRequestFocusEnabled(false);
        PanelRight1.setLayout(new java.awt.GridLayout(10, 0, 10, 5));

        LblUserName.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        LblUserName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LblUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/green/ams/assets/icons/user-removebg-preview.png"))); // NOI18N
        LblUserName.setText(bundle.getString("USER.LblUserName.text")); // NOI18N
        LblUserName.setAlignmentX(0.5F);
        LblUserName.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        PanelRight1.add(LblUserName);

        UPLblFullName.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        UPLblFullName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UPLblFullName.setText(bundle.getString("USER.UPLblFullName.text")); // NOI18N
        PanelRight1.add(UPLblFullName);

        UPTFFullName.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        UPTFFullName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        UPTFFullName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 104, 73), 3, true));
        UPTFFullName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UPTFFullName.setMaximumSize(new java.awt.Dimension(100, 200));
        PanelRight1.add(UPTFFullName);

        UPLblAddress.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        UPLblAddress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UPLblAddress.setText(bundle.getString("USER.UPLblAddress.text")); // NOI18N
        PanelRight1.add(UPLblAddress);

        UPTFAddress.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        UPTFAddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        UPTFAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 104, 73), 3, true));
        UPTFAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PanelRight1.add(UPTFAddress);

        UPLblPhone.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        UPLblPhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UPLblPhone.setText(bundle.getString("USER.UPLblPhone.text")); // NOI18N
        PanelRight1.add(UPLblPhone);

        UPTFPhone.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        UPTFPhone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        UPTFPhone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 104, 73), 3, true));
        UPTFPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PanelRight1.add(UPTFPhone);

        UPLblResetPassword.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        UPLblResetPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        UPLblResetPassword.setText(bundle.getString("USER.UPLblResetPassword.text")); // NOI18N
        PanelRight1.add(UPLblResetPassword);

        UPTFResetPassword.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        UPTFResetPassword.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        UPTFResetPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(33, 104, 73), 3, true));
        UPTFResetPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PanelRight1.add(UPTFResetPassword);

        PanelContainer1.add(PanelRight1);

        FormUserProfile.add(PanelContainer1);

        PanelButtons1.setBackground(new java.awt.Color(245, 255, 243));

        BtnSave.setBackground(new java.awt.Color(33, 104, 73));
        BtnSave.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        BtnSave.setForeground(new java.awt.Color(255, 255, 255));
        BtnSave.setText(bundle.getString("USER.BtnSave.text")); // NOI18N
        BtnSave.setAlignmentY(0.0F);
        BtnSave.setBorder(null);
        BtnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSave.setDefaultCapable(false);
        BtnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSave.setMaximumSize(new java.awt.Dimension(80, 30));
        BtnSave.setMinimumSize(new java.awt.Dimension(40, 15));
        BtnSave.setPreferredSize(new java.awt.Dimension(100, 40));
        PanelButtons1.add(BtnSave);

        BtnBack1.setBackground(new java.awt.Color(121, 110, 113));
        BtnBack1.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        BtnBack1.setForeground(new java.awt.Color(255, 255, 255));
        BtnBack1.setText(bundle.getString("USER.BtnBack1.text")); // NOI18N
        BtnBack1.setAlignmentY(0.0F);
        BtnBack1.setBorder(null);
        BtnBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBack1.setDefaultCapable(false);
        BtnBack1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBack1.setMaximumSize(new java.awt.Dimension(80, 30));
        BtnBack1.setMinimumSize(new java.awt.Dimension(40, 15));
        BtnBack1.setPreferredSize(new java.awt.Dimension(100, 40));
        BtnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBack1ActionPerformed(evt);
            }
        });
        PanelButtons1.add(BtnBack1);

        FormUserProfile.add(PanelButtons1);

        PanelUserProfile.add(FormUserProfile, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelUserProfile);
        PanelUserProfile.setBounds(0, 0, 1366, 768);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSignOutActionPerformed
        // TODO add your handling code here:

        user = null;
        this.dispose();
        app = new APP();
        app.setVisible(true);

    }//GEN-LAST:event_BtnSignOutActionPerformed

    private void nav_rateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nav_rateMouseClicked
        // TODO add your handling code here:

        MoveTo(PanelHome, PanelFeedback);

    }//GEN-LAST:event_nav_rateMouseClicked

    private void BtnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSendActionPerformed

        feedback = new Feedback();

        feedback.setFull_name(TFFullName.getText().trim());
        feedback.setEmail_address(TFEmailAddress.getText().trim());
        feedback.setPhone_number(TFPhone.getText().trim());
        feedback.setMessage(TAMessage.getText().trim());
        feedback.setCurrent_date(current_date);

        if (isFeedbackValid(feedback)) {

            if (user_controller.Feedback(feedback)) {
                JOptionPane.showMessageDialog(PanelContainer, "Your Feedback Inserted Successfully");

                // Create and show modal dialog with the rating component
                JDialog dialog = new JDialog((Frame) null, "Rate Us!", true);
                dialog.setSize(400, 200);
                dialog.setLayout(new BorderLayout());
                dialog.setLocationRelativeTo(null);
                dialog.setBackground(new java.awt.Color(245, 255, 243));

                // Anonymous instance of the rating component
                StarRating ratingComponent = new StarRating();
                dialog.add(ratingComponent, BorderLayout.CENTER);

                JPanel btnPanel = new JPanel();
                btnPanel.setBackground(new java.awt.Color(245, 255, 243));
                dialog.add(btnPanel, BorderLayout.SOUTH);

                // Submit button
                JButton submit = new JButton("Submit");
                btnPanel.add(submit);
                submit.setBackground(new java.awt.Color(33, 104, 73));
                submit.setForeground(Color.WHITE);
                submit.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N

                dialog.setVisible(true); // blocks until dialog is closed
                submit.addActionListener(e -> {
                    // Use the result after dialog closes
                    final int selectedRating = ratingComponent.getRating();

                    evaluate = new Evaluate();

                    evaluate.setFeedback_id(feedback.getId());
                    evaluate.setRate(selectedRating);

                    dialog.dispose(); // close dialog
                });
                MoveTo(PanelFeedback, PanelHome);
            }

        } else {
            JOptionPane.showConfirmDialog(PanelContainer, "Failed to send");

        }

    }//GEN-LAST:event_BtnSendActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:

        MoveTo(PanelFeedback, PanelHome);

    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSettingMouseClicked
        // TODO add your handling code here:
        
        MoveTo(PanelHome, PanelUserProfile);
    }//GEN-LAST:event_BtnSettingMouseClicked

    private void BtnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBack1ActionPerformed
        // TODO add your handling code here:
        
        MoveTo(PanelUserProfile, PanelHome);
    }//GEN-LAST:event_BtnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(USER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new USER().setVisible(true);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnBack1;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnSend;
    private javax.swing.JLabel BtnSetting;
    private javax.swing.JButton BtnSignOut;
    private javax.swing.JLabel BtnSupport;
    private javax.swing.JLabel BtnUserProfile;
    private javax.swing.JPanel FormFeedback;
    private javax.swing.JPanel FormUserProfile;
    private javax.swing.JLabel LblEmailAddress;
    private javax.swing.JLabel LblMessage;
    private javax.swing.JLabel LblName;
    private javax.swing.JLabel LblName2;
    private javax.swing.JLabel LblPhone;
    private javax.swing.JLabel LblUserName;
    private javax.swing.JPanel PanelButtons;
    private javax.swing.JPanel PanelButtons1;
    private javax.swing.JPanel PanelContainer;
    private javax.swing.JPanel PanelContainer1;
    private javax.swing.JPanel PanelFeedback;
    private javax.swing.JPanel PanelHome;
    private javax.swing.JPanel PanelLeft;
    private javax.swing.JPanel PanelLeft1;
    private javax.swing.JPanel PanelRight;
    private javax.swing.JPanel PanelRight1;
    private javax.swing.JLabel PanelTitle;
    private javax.swing.JPanel PanelUserProfile;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTextArea TAMessage;
    private javax.swing.JTextField TFEmailAddress;
    private javax.swing.JTextField TFFullName;
    private javax.swing.JTextField TFPhone;
    private javax.swing.JLabel UPLblAddress;
    private javax.swing.JLabel UPLblFullName;
    private javax.swing.JLabel UPLblPhone;
    private javax.swing.JLabel UPLblResetPassword;
    private javax.swing.JTextField UPTFAddress;
    private javax.swing.JTextField UPTFFullName;
    private javax.swing.JTextField UPTFPhone;
    private javax.swing.JTextField UPTFResetPassword;
    private javax.swing.JPanel UserNavigation;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel nav_consultant;
    private javax.swing.JLabel nav_location;
    private javax.swing.JLabel nav_rate;
    private javax.swing.JLabel nav_sample;
    // End of variables declaration//GEN-END:variables

    private void Start() {
        UserNavigation.setVisible(false);
        PanelFeedback.setVisible(false);
        PanelUserProfile.setVisible(true);
    }

    private void MoveTo(JPanel o1, JPanel o2) {
        o1.setVisible(false);
        o2.setVisible(true);
    }

    private void switchLanguage() {

        // Reload ResourceBundle with correct package
        GLOBAL.bundle = ResourceBundle.getBundle("green.ams.Bundle", GLOBAL.currentLocale);

        // Update UI Components
        GLOBAL.updateTextFields(this, "USER", GLOBAL.bundle);
    }

    public static boolean isFeedbackValid(Feedback feedback) {
        return feedback.getFull_name() != null && !feedback.getFull_name().isEmpty()
                && feedback.getEmail_address() != null && !feedback.getEmail_address().isEmpty()
                && feedback.getPhone_number() != null && !feedback.getPhone_number().isEmpty()
                && feedback.getMessage() != null && !feedback.getMessage().isEmpty();
    }

}
